Issue with the parser show bgp vrf maxis_MC_ACP ipv4 unicast 10.33.10.132/31

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 529, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 568, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/conf/base/device.py", line 566, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/aliesmaeilicharkhab/.pyenv/versions/3.8.17/lib/python3.8/site-packages/genie/libs/parser/iosxr/show_bgp.py", line 8310, in cli
    next_hop_dict = as_path_dict.setdefault('bgp_peer_neighbor_ip', {}).setdefault(bgp_peer_neighbor_ip, {})
UnboundLocalError: local variable 'as_path_dict' referenced before assignment
